apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sjm-py-tastpa-203
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sjm-py-tastpa-203 
  name: sjm-py-tastpa-203
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sjm-py-tastpa-203 
